# Generated by Django 4.1.7 on 2023-02-26 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_collection_customer_order_product_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
            preserve_default=False,
        ),
    ]
