# Generated by Django 4.1.7 on 2023-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
