# Generated by Django 4.1.7 on 2023-02-27 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_collection_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
